### ISSUE TITLE
Produce boilerplate code

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#1]
- [DONE] README.rst
- [DONE] INSTALL.rst and Poetry
- [DONE] Django and docker-compose.yml
- [DONE] pre-commit
- [DONE] yapf
- [DONE] flake8
- [DONE] unittests
- [DONE] Layer (dynaconf-like) settings
- [DONE] Dockerfile
- [DONE] Github workflows

**Comment by dmugtasimov** [comment]
@buckyroberts I think I have done with the biolerplate. Please, try it out. Specifically I would appreciate if you could follow all steps in `INSTALL.rst` and let me know if there are any issues. Ideally you should just do what is written in the exact order and it should work.

**Comment by dmugtasimov** [comment]
Oh, and I did not add Celery and other dependencies, because there is not Python code that depends on it. I will add all the dependencies as soon as I add the corresponding code.

**Comment by AbhayAysola** [comment]
Hi, I followed the steps in `INSTALL.rst` and I didn't have any issues. Just letting you know :)

**Comment by dmugtasimov** [comment]
@AbhayAysola thank you

**Comment by zinoadidi** [comment]
@dmugtasimov is there some sort of feature documentation to look at at the moment or whats the plan for it

**Comment by dmugtasimov** [comment]
@zinoadidi you may review the content of https://github.com/thenewboston-developers/thenewboston-node/projects/1 project to have an idea

**Comment by dmugtasimov** [comment]
Please, contact @buckyroberts for the general roadmap of thenewboston
