### ISSUE TITLE
Expose online API documentation

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#101]
Expose online API documentation: https://www.django-rest-framework.org/topics/documenting-your-api/

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/117

**Comment by dmugtasimov** [comment]
@andbortnik please make the requested change and merge by yourself

**Comment by andbortnik** [comment]
Merged
