### ISSUE TITLE
Network Initialization and PV Scheduling

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-node#105]
DEPENDS ON:
- https://github.com/thenewboston-developers/thenewboston-node/issues/272

Documentation:
https://docs.google.com/document/d/1kU0qxuJQC8PybSEZ8OHOUldx8b7TFJg9c79TjZrsVHQ/edit?usp=sharing

**Comment by dmugtasimov** [comment]
A related issue: https://github.com/thenewboston-developers/thenewboston-node/issues/226

**Comment by dmugtasimov** [comment]
Will be reviewed for gaps as a part of Block confirmation process milestone
