### ISSUE TITLE
List account transactions API end-point

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#109]
TODO:
- GET /api/v1/accounts/{id}/transactions/
- Pagination
- Ordering asc/desc chronologically
- If node does not have complete blockchain (all blocks till number 0) and transaction beyond known blocks are requested raise NotImplemented error (later we will have to implement sync initialization or otherwise redirection of client to get the entire list of transaction from somewhere else, for example from current PV)
- Use serializer based on transaction dataclass
- Add a TODO about a need of caching implementation

**Comment by fonar** [comment]
@dmugtasimov i want to propose of using the "drf-nested-routers" library that i sucessfully used for several projects.
It will allow to have the drf transactions viewset that will be nested under acounts viewset, keeping them separate.
that is very usefull and keeping clean architecture for api's in drf-style.
What do you think?
https://github.com/alanjds/drf-nested-routers

**Comment by dmugtasimov** [comment]
@fonar sure, go ahead

**Comment by fonar** [comment]
@dmugtasimov should this API be 
`GET /api/v1/account_states/{id}/transactions/`
instead of
`GET /api/v1/accounts/{id}/transactions/`
as mentioned in issue description?

**Comment by fonar** [comment]
@dmugtasimov in PR logic and tests is not complete and i will improve, just 3 quick qustions: (1) if endpoint URL is ok (2) what blockchain iterface (mixin) to use (3) how to check for imcomplete blockchain. I see this in code but don't have full understanding how to use it.

**Comment by dmugtasimov** [comment]
@fonar replied in discord

**Comment by fonar** [comment]
@dmugtasimov ready for review

**Comment by dmugtasimov** [comment]
@fonar thank you, merged. Please, address this comment https://github.com/thenewboston-developers/thenewboston-node/pull/341/files#r698550152 in another PR

**Comment by dmugtasimov** [comment]
@fonar I isolated and corrected incomplete blockchain related logic: https://github.com/thenewboston-developers/thenewboston-node/pull/370

**Comment by fonar** [comment]
@dmugtasimov added PR #371

**Comment by dmugtasimov** [comment]
@fonar thank you, merged
