### ISSUE TITLE
Implement file lock on file blockchain update

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#115]
TODO:
- Use a single `file.lock` for account root file and add block placed in the blockchain root (`base_directory` kwarg)
- Lock on enter to `add_block()` and unlock on exit -> raise `BlockchainLockedError` if trying to operate on locked blockchain
- Lock on enter to `add_account_root_file()` and unlock on exit -> raise `BlockchainLockedError` if trying to operate on locked blockchain
- All other submethods must just check that the blockchain is locked -> raise `BlockchainUnlockedError` if the blockchain is not locked as expected
- Implement as method decorators

**Comment by andbortnik** [comment]
@dmugtasimov Ready for review https://github.com/thenewboston-developers/thenewboston-node/pull/164

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you. Please, add unittests that test locking features of FileBlockchain.

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/186
