### ISSUE TITLE
Secret keys leaked in GitHub Repos

### ISSUE THREAD

**Issue by classicevent** [thenewboston-developers/thenewboston-node#136]
**Bug Description**
While analyzing the GitHub repos, I found that there are some secret keys being left open in the wild. It might lead to security threat for thenewboston.

**Steps to Reproduce**

1. Go to the links mentioned below
2. See the secret keys

**Links and Secrets**
* https://github.com/thenewboston-developers/thenewboston-node/blob/c6a812343bc42ad02614def469d8bad46ea3982d/thenewboston_node/project/settings/templates/.env

`THENEWBOSTON_NODE_SECRET_KEY=90oqi[f[ohfipuuapugrp83yq09=40=oasdngkj`

* https://github.com/thenewboston-developers/Website-API/commit/89129f8b3e60a25232b59e4ef469c0bb557a69fd#diff-f7a16228131ae92457c22657bb33458207a7578b8cdb6ff796153916fa67a22d

`SECRET_KEY = 'g#$0(*8%8af27k7-e!ll^!-4yxomcx8ljv_o&_z*zhvi)f8&e7'`

* https://github.com/thenewboston-developers/thenewboston-node/blob/854abbf8814729eeca9973396f1ef6a61fed7a3f/thenewboston_node/project/settings/templates/settings.unittests.py

`SECRET_KEY = '90oqi[f[ohfipuuapugrp83yq09=40=oasdngkj'`

**Expected behavior**
Secrets should not have been left publicly

**Actual behavior**
Secret keys are being leaked

**Account Number**
362019f00e72fbe002497c667ab0d4fe4f4ac1ff8785724d0a69d39fe957fead

**Comment by ThaDeveloper** [comment]
The WesiteAPI was resolved sometimes back(as indicated from change history), we currently using env variables

**Comment by andbortnik** [comment]
Thanks @classicevent 

Secret key variable `SECRET_KEY` in https://github.com/thenewboston-developers/thenewboston-node/blob/854abbf8814729eeca9973396f1ef6a61fed7a3f/thenewboston_node/project/settings/templates/settings.unittests.py is used for unittests only.

File https://github.com/thenewboston-developers/thenewboston-node/blob/c6a812343bc42ad02614def469d8bad46ea3982d/thenewboston_node/project/settings/templates/.env is just a template. `THENEWBOSTON_NODE_SECRET_KEY` is supposed to be changed to the real node's secret key during node's deployment.

So no security issues here.

**Comment by classicevent** [comment]
Understood, thanks!
