### ISSUE TITLE
Migrate all models to new validators

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#161]
In PR https://github.com/thenewboston-developers/thenewboston-node/pull/154/files#diff-21b702ae2b51eab764bcb0017f28589b8e8eabd55f4653818d711c4eb6839922 you can see new validators are used. Refactor the rest of the models to use them. Add new validators as needed

**Comment by andbortnik** [comment]
@dmugtasimov Ready for review https://github.com/thenewboston-developers/thenewboston-node/pull/191
