### ISSUE TITLE
Register node block type

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#162]

**Comment by dmugtasimov** [comment]
Blockchain state example:

```json
{
    "account_states": {
        "1be4f03ab7ea1184dbb5e4ff53b8cf0fe1cc400150ca1476fcd10546c1b3cd6a": {
            "balance": 1,
            "balance_lock": "1be4f03ab7ea1184dbb5e4ff53b8cf0fe1cc400150ca1476fcd10546c1b3cd6a"
        },
        "4d3cf1d9e4547d324de2084b568f807ef12045075a7a01b8bec1e7f013fc3732": {
            "balance": 4,
            "balance_lock": "4d3cf1d9e4547d324de2084b568f807ef12045075a7a01b8bec1e7f013fc3732"
        },
        "8d3bf5323afa7a8c6bc9418288e96491a0434a98925bf392835bfdb5a4f817ff": {
            "balance": 54,
            "balance_lock": "8d3bf5323afa7a8c6bc9418288e96491a0434a98925bf392835bfdb5a4f817ff"
        }
    },
    "last_block_identifier": "d606af9d1d769192813d71051148ef1896e3d85062c31ad3e62331e25d9c96bc",
    "last_block_number": 100,
    "last_block_timestamp": "2021-01-01T00:00:00",
    "next_block_identifier": "18266e8fb5fba0ca9a0078d799c73ca34512c229519b1d021b8c2b78ef5f70b7"
}
```

**Comment by dmugtasimov** [comment]
@buckyroberts Please, take a look at blockchain state file example. Notice there is "network_addresses" attribute.

With such design we have several important points:
1. Not only a node, but anyone with an account on the network may declare its network address. We might not need it now, but I think we should keep it. There may be edge case like a regular user user decided to run a node on existing account or a node decided to shut down, but keep the account. I think we should not impose limitations here.
2. An account may declare multiple addresses
3. An account may declare different type of addresses and we leave it other node implementation if they support those transports or not

**Comment by dmugtasimov** [comment]
@buckyroberts I am designing NodeRegistrationSignedChangeRequest now. Actually, let's call it NetworkAddressesRegistrationSignedChangeRequest?

Here is my question: should an account owner pay for the address registration / change?

**Comment by dmugtasimov** [comment]
I think we are fine if the same address is registered with 2 accounts, since it is easy to check which account is actually holds the address (the one that can produce a signed response when called on that address over API)

**Comment by AbhayAysola** [comment]
> I think we are fine if the same address is registered with 2 accounts, since it is easy to check which account is actually holding the address (the one that can produce a signed response when called on that address over API)

What if both of them produce a valid response?

**Comment by dmugtasimov** [comment]
@AbhayAysola It would be fine since physical transport is not important as long as node serve accordingly

**Comment by AbhayAysola** [comment]
> @AbhayAysola It would be fine since physical transport is not important as long as node serve accordingly

Alright, thanks for clarifying

**Comment by dmugtasimov** [comment]
Intermediate merge to avoid painful rebase: https://github.com/thenewboston-developers/thenewboston-node/pull/166

**Comment by dmugtasimov** [comment]
Intermediate merge to avoid painful rebase: https://github.com/thenewboston-developers/thenewboston-node/pull/167

**Comment by dmugtasimov** [comment]
More refactoring: https://github.com/thenewboston-developers/thenewboston-node/pull/169

**Comment by dmugtasimov** [comment]
More: https://github.com/thenewboston-developers/thenewboston-node/pull/170

**Comment by dmugtasimov** [comment]
More refactoring: https://github.com/thenewboston-developers/thenewboston-node/pull/171

**Comment by dmugtasimov** [comment]
Implemented: https://github.com/thenewboston-developers/thenewboston-node/pull/173

**Comment by dmugtasimov** [comment]
Compacted keys: https://github.com/thenewboston-developers/thenewboston-node/pull/174

**Comment by dmugtasimov** [comment]
Brush up: https://github.com/thenewboston-developers/thenewboston-node/pull/175

**Comment by dmugtasimov** [comment]
Serialization/deserialization refactoring: https://github.com/thenewboston-developers/thenewboston-node/pull/176

**Comment by dmugtasimov** [comment]
dataclass_json removed: https://github.com/thenewboston-developers/thenewboston-node/pull/177

**Comment by dmugtasimov** [comment]
mixin brush up: https://github.com/thenewboston-developers/thenewboston-node/pull/178

**Comment by dmugtasimov** [comment]
hexstr datatype: https://github.com/thenewboston-developers/thenewboston-node/pull/180

**Comment by dmugtasimov** [comment]
let's consider it done. improvements will be done in other tasks
