### ISSUE TITLE
Implement validation on network address registration related models

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#163]
TODO:
- Implement:
```
    def validate(self, blockchain, block_number: Optional[int] = None):
        # TODO(dmu) CRIRICAL: Implement
        return
```
- Validate that the provided addresses are non-empty and valid URIs (providing empty list is fine because it is the away we unregister a node from the network - unittest it)

Note: no need to check availability of the network addresses as it may change with time anyway

**Comment by dmugtasimov** [comment]
to be done after https://github.com/thenewboston-developers/thenewboston-node/issues/162

**Comment by andbortnik** [comment]
@dmugtasimov What is valid network address? 

1. Just hostname identified by ipv4/ipv6/domain name? 
2. Can it be CIDR like `192.168.100.14/24`?
3. Can it contain a port number like `192.168.100.14:80`?
4. Can it contain protocol like `http://mydomain`

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/230

**Comment by dmugtasimov** [comment]
1. it must be a valid URI
2. no
3. yes
4. yes

**Comment by dmugtasimov** [comment]
@andbortnik see above ^^^

Also there is a question in the PR

**Comment by dmugtasimov** [comment]
@andbortnik Let's remove FQDN validation. 1) it does not support `localhost` 2) we may need other `/etc/hosts` aliases for testing. After all it is signer responsibility to provide resolvable hostname. At first I did not want to have any validation of address at all, but decided to validate for being URI to explicitly declare what we expect as an address.

**Comment by dmugtasimov** [comment]
@andbortnik please, also address comments from PR

**Comment by andbortnik** [comment]
@dmugtasimov Please take another look

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you. Please, address an extra comment in some other PR
