### ISSUE TITLE
Refactor compaction algorithm, so it detects hexstr type and automatically converts to binary

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#179]

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/220

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you. There is a couple of comments in the PR. Please, address them in some other PR

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/235

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you. Please, address comments in another PR

**Comment by andbortnik** [comment]
@dmugtasimov Seems like you fixed most of the comments. Please review the rest https://github.com/thenewboston-developers/thenewboston-node/pull/248

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you
