### ISSUE TITLE
Assert that all dataclass attributes of AccountState are optional [complete for 500 TNBC]

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#205]
The task is to implement this TODO:
```
# TODO(dmu) CRITICAL: Assert all attributes are optional
```

We need to assert that all dataclass attributes of AccountState are optional, so if later a developer creates new attribute which is non-optional the code will fail-fast.

**Comment by AnonymousDapper** [comment]
Here's a little concept I put together using `__new__`.This just checks on every instantiation, but could easily be swapped over to a classmethod and only run once.

@dmugtasimov I could even make a new AllOptionalBaseDataclass that enforces all Optional types, if this is to be used elsewhere.

```py
from dataclasses import dataclass
from test import AllOptionalDataclass
from typing import Optional

@dataclass
class Test(AllOptionalDataclass):
    a: Optional[int]
    b: Optional[str]
    c: float
    d: Optional[int]

model = Test(5, None, 4.3, None)


>> TypeError: Field 'c' should be Optional[float], not float
```

**Comment by dmugtasimov** [comment]
@AnonymousDapper it is nice that you can handle metaclasses, but this looks like overengineering for this. Also we not as flexible as we need. Later we might figure out that we need one or more mandatory attributes and this solution will have to be replaced completely.

I need a simple for-loop with `assert` statement which checks that each attribute is optional. This way we can easily add exceptions.

**Comment by AnonymousDapper** [comment]
Hmm, ok. You just want a static method in the module then?

**Comment by dmugtasimov** [comment]
@AnonymousDapper added comments to the PR, please, fix

**Comment by dmugtasimov** [comment]
@AnonymousDapper merged, thank you. You will get paid soon.

**Comment by dmugtasimov** [comment]
@AnonymousDapper please, provide your TNBC account number to get paid

**Comment by AnonymousDapper** [comment]
My address is `8125ed8cdc5cb2bc8cb3c4297e4e8f6e37db18e880d2b564071fa10521df0698`

**Comment by dmugtasimov** [comment]
@AnonymousDapper coins sent, please, confirm that you have received them

**Comment by dmugtasimov** [comment]
I keep the task assigned to myself, since I paid from my personal account and now I need to claim the coin from the government.

**Comment by AnonymousDapper** [comment]
Indeed received, thank you.

**Comment by dmugtasimov** [comment]
@manishram please, reimburse to 757d598308bf1e2943bd1a9fc34ae7b8951ca864d64228b59e62614b27ddefc4
