### ISSUE TITLE
Make blockchain format documentation available from running node

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#208]
TODO:
- Add link to index page
- Serve both RST and HTML formats
- Generate it at runtime and cache (use database as cache storage - or is it faster just generate everytime without caching) or pregenerate (put to cache) at server start - use standard Django means of page caching as much as possible

**Comment by dmugtasimov** [comment]
Looks like duplicate: https://github.com/thenewboston-developers/thenewboston-node/issues/217

**Comment by andbortnik** [comment]
@dmugtasimov Do we really need to involve Django here? The only job it will have to do is serving static files.

Wouldn't it be better to delegate it to Nginx? We can generate documentation files on a building stage. Then we let Nginx manage these doc files and cache them.

**Comment by dmugtasimov** [comment]
@andbortnik it seems more complex job to serve static files from nginx to me, but you see it the other way let's give it a shot

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/264

**Comment by dmugtasimov** [comment]
@andbortnik please, address comments

Please, be aware of not breaking autodeployment. Example: https://github.com/thenewboston-developers/thenewboston-node/actions/runs/1046852958

**Comment by andbortnik** [comment]
@dmugtasimov 

1. Please check the changes in CI merged to `master` https://github.com/thenewboston-developers/thenewboston-node/compare/c5f3b3ee87ee54caf583e2068551e86e2e6a5d77..f6f5af9d479f2b682b4275d2468196aee80c598f
1. Build stage works but the deployment stage fails. Looks like there is no space left https://github.com/thenewboston-developers/thenewboston-node/runs/3124070937
        ```ERROR: for node  failed to register layer: Error processing tar file(exit status 1): write /root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/virtualenv/seed/wheels/embed/pip-19.1.1-py2.py3-none-any.whl: no space left on device```
1. Review the PR again

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you, looks great
