### ISSUE TITLE
Review blockchain structure documentation

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#218]
The docs: https://github.com/thenewboston-developers/thenewboston-node/wiki/thenewboston-blockchain-format

TODO:
- Reread the docs and if there are improvement required
- Review and update docstrings for dataclass attributes

**Comment by dmugtasimov** [comment]
@led76marx PR is best case scenario. If not then either modify wiki or copy to google docs and modify in suggest mode. Last resort: add comments that describe required changes in this issue.

**Comment by led76marx** [comment]
No worries - will handle tomorrow - thx for keeping track of this task.

**Comment by dmugtasimov** [comment]
@led76marx merged this one https://github.com/thenewboston-developers/thenewboston-node/pull/231 with some tiny changes. Thank you for the docs refinement.
