### ISSUE TITLE
Remove exposed 80 and defaut nginx welcome page from image

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#221]
TODO:
- The best case: inject (by nginx) link to blockchain root available over HTTP into the index page returned by Django (see http://nginx.org/en/docs/http/ngx_http_sub_module.html )

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/237

**Comment by dmugtasimov** [comment]
@andbortnik How is "remove defaut nginx welcome page" addressed?

**Comment by dmugtasimov** [comment]
@andbortnik see comments in PR as well

**Comment by andbortnik** [comment]
> @andbortnik How is "remove defaut nginx welcome page" addressed?

@dmugtasimov Can you explain please what this means? Please see answers in the PR.

**Comment by dmugtasimov** [comment]
> > @andbortnik How is "remove defaut nginx welcome page" addressed?
> 
> @dmugtasimov Can you explain please what this means? Please see answers in the PR.

By default nginx has welcome page available at HTTP 80. Although we do no expose it with docker, let's remove it internally in nginx.

**Comment by dmugtasimov** [comment]
@andbortnik reviewed and replied

**Comment by andbortnik** [comment]
> > > @andbortnik How is "remove defaut nginx welcome page" addressed?
> > 
> > 
> > @dmugtasimov Can you explain please what this means? Please see answers in the PR.
> 
> By default nginx has welcome page available at HTTP 80. Although we do no expose it with docker, let's remove it internally in nginx.

@dmugtasimov 
Right. Default nginx configuration is located in `/etc/nginx/conf.d/default.conf`. But the directory is masked by the mounted volume and it has only our config. So port 80 is not open. No action required.

Please review the PR

**Comment by dmugtasimov** [comment]
@andbortnik thank you, merged

**Comment by dmugtasimov** [comment]
Ports brush up: https://github.com/thenewboston-developers/thenewboston-node/pull/256
