### ISSUE TITLE
Add method to the blockchain to get node current role by account number

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#223]
TODO:
- it should be a method on a blockchain class
- values (implement enum): null, 1 - PV, 2 - CV, 3 - regular
- add to GET `/api/v1/nodes/{}/` response as `role` attribute
- a node is CV if it is scheduled as PV in the future, PV if it is current PV, null if a node is not declared on the account and 3 otherwise

**Comment by dmugtasimov** [comment]
Questions:
- Node blockchain is always delayed from PV blockchain. What should we do if node's role has changed, but it does not know about it yet?

**Comment by fonar** [comment]
PR #327

**Comment by fonar** [comment]
@dmugtasimov can you please review and if code is ok, tell me how detailed tests should be implemented: tests for blockchain method - for all node types? tests for api endpoint - for all node types?

**Comment by dmugtasimov** [comment]
@fonar please, address the comments. We should have at least unittests that cover all the code changes (API unittests should do it). If you see that there is need to add unittests at lower levels to cover some special cases, please, do. But we do need super small unittests that cover tiny pieces of code with mocks everywhere. I prefer a practical approach where there just enough unittests to server their purpose - to catch bugs.

**Comment by dmugtasimov** [comment]
@fonar the PR looks good, but, please, squash commit into one and address minor comments

**Comment by fonar** [comment]
@dmugtasimov please take a look at my comments on your review in PR #327

**Comment by dmugtasimov** [comment]
@fonar replied. Please, squash the commits and I will merge. I will review those comment myself after merge to see what issues you faced and the best to resolve them (I will provide and extra PR, so you can see what changed).

**Comment by fonar** [comment]
@dmugtasimov done

**Comment by dmugtasimov** [comment]
@fonar merged, thank you

**Comment by dmugtasimov** [comment]
@dmugtasimov FYI: https://github.com/thenewboston-developers/thenewboston-node/pull/338

**Comment by dmugtasimov** [comment]
@fonar FYI: https://github.com/thenewboston-developers/thenewboston-node/pull/339
