### ISSUE TITLE
Implement GET /api/v1/node/{id}/ API end-point

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#224]
TODO:
- Return information about declared node
- If node is not declared or undeclared respond with HTTP404
- id is account number or special value
- if id is "self" return information about the node that was called
- if id is "pv" return information about current pv
- Use Node model to construct serializer

**Comment by andbortnik** [comment]
@dmugtasimov How to get a primary validator from blockchain?

**Comment by dmugtasimov** [comment]
@andbortnik use some stub method for now. I will implement it with PV scheduling.

**Comment by dmugtasimov** [comment]
@andbortnik I reviewed. Looks good.

**Comment by dmugtasimov** [comment]
@andbortnik you can use get_primary_validator() from https://github.com/thenewboston-developers/thenewboston-node/pull/246 now

**Comment by andbortnik** [comment]
@dmugtasimov Implemented PV part. Please review.

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you
