### ISSUE TITLE
REST API method to get path to latest available blockchain state

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#252]
TODO:
- Use `thenewboston_node.business_logic.blockchain.file_blockchain.get_blockchain_state_filename_meta`
- GET /api/v1/blockchain-states-meta/?limit=&offset=&ordering=
- ordering by block_number in both directions must be supported. do not forget to handle special case of blockchain genesis state ( implement by yielding blockchain states in either direction)
- GET /api/v1/blockchain-states-meta/{block_number}/  (if leading zeros are provided then they should be striped from `block_number`
- Use `blockchain` application
- Base "urls" on "network_addresses" of the declared node

Response example:
```
[
        {
		"last_block_number": null,
                "url_path": "/blockchain/account-root-files/0/0/0/0/0/0/0/0/000000000!-arf.msgpack.xz",
		"urls": ["http://3.143.205.184:8555/blockchain/account-root-files/0/0/0/0/0/0/0/0/000000000!-arf.msgpack.xz"]
	},
	{
		"last_block_number": 10,
                "url_path": "/blockchain/account-root-files/0/0/0/0/0/0/0/0/0000000010-arf.msgpack.xz",
		"urls": ["http://3.143.205.184:8555/blockchain/account-root-files/0/0/0/0/0/0/0/0/0000000010-arf.msgpack.xz"]
	}
]
```

Use this code for pagination:

```
from collections import OrderedDict

from rest_framework.pagination import LimitOffsetPagination
from rest_framework.response import Response


class CustomLimitOffsetPaginationBase(LimitOffsetPagination):
    default_limit = 5
    max_limit = 20

    def get_paginated_dict(self, data):
        raise NotImplementedError('Must be implemented in a child class')

    def get_paginated_response(self, data):
        return Response(self.get_paginated_dict(data))


class CustomLimitOffsetPagination(CustomLimitOffsetPaginationBase):

    def get_paginated_dict(self, data):
        return OrderedDict((('count', self.count), ('results', data)))
```

**Comment by dmugtasimov** [comment]
@andbortnik I rename `path` to `url_path`

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/291

What do we do if the requested node is unregistered in the blockchain? In the PR `urls` is empty in this case.

**Comment by dmugtasimov** [comment]
@andbortnik let's serve as usual. Just put a HIGH priority TODO about it. Because normally if a node unregisters itself it should also become offline and also even if it does not since it is unregistered other nodes should not consider it as available and therefore do not make API requests to it.

**Comment by dmugtasimov** [comment]
@andbortnik I added some comments (maybe I will have more later). The main issue is that representation logic was put into business logic. Please, address the comments.

**Comment by dmugtasimov** [comment]
@andbortnik also if you wish you may submit changes in smaller PRs. I do it sometimes myself: just abandon the entire large PR and make many more smaller PRs untill I cover everything I had in the large PR originally. This up to you, just a suggestion.

**Comment by andbortnik** [comment]
@dmugtasimov Fixed

**Comment by dmugtasimov** [comment]
@andbortnik looks like you amended your changes with a merge commit. Please, fix it. Also, please address new comments.

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you

**Comment by dmugtasimov** [comment]
TODO:
- Also allow `null` and `genesis` special values for block number along with -1

**Comment by dmugtasimov** [comment]
@andbortnik Refactoring: https://github.com/thenewboston-developers/thenewboston-node/pull/308

will do more soon

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/309

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/311

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/312

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/313

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/314

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/315

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/316

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/317

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/318

**Comment by dmugtasimov** [comment]
@andbortnik please, work on TODOs from here: https://github.com/thenewboston-developers/thenewboston-node/issues/252#issuecomment-894393425

**Comment by dmugtasimov** [comment]
@andbortnik serializer-based implementation: https://github.com/thenewboston-developers/thenewboston-node/pull/326

**Comment by dmugtasimov** [comment]
@andbortnik solution for performance: https://github.com/thenewboston-developers/thenewboston-node/pull/328

**Comment by dmugtasimov** [comment]
@andbortnik is this PR https://github.com/thenewboston-developers/thenewboston-node/pull/329 ready for merge?

**Comment by andbortnik** [comment]
@dmugtasimov Ready for review:
- https://github.com/thenewboston-developers/thenewboston-node/pull/329
- https://github.com/thenewboston-developers/thenewboston-node/pull/350
- https://github.com/thenewboston-developers/thenewboston-node/pull/351

**Comment by dmugtasimov** [comment]
@andbortnik https://github.com/thenewboston-developers/thenewboston-node/pull/329 merged, thank you

**Comment by dmugtasimov** [comment]
@andbortnik please, address the comment for https://github.com/thenewboston-developers/thenewboston-node/pull/350

**Comment by dmugtasimov** [comment]
@andbortnik rebase required: https://github.com/thenewboston-developers/thenewboston-node/pull/351

**Comment by dmugtasimov** [comment]
@andbortnik https://github.com/thenewboston-developers/thenewboston-node/pull/350 merged, thank you

**Comment by dmugtasimov** [comment]
Fixup: https://github.com/thenewboston-developers/thenewboston-node/pull/366

**Comment by dmugtasimov** [comment]
@andbortnik Thank you https://github.com/thenewboston-developers/thenewboston-node/pull/351 is merged

**Comment by dmugtasimov** [comment]
@andbortnik thank you, https://github.com/thenewboston-developers/thenewboston-node/pull/364 merged

**Comment by dmugtasimov** [comment]
@andbortnik is there anything left to do in this task?

**Comment by andbortnik** [comment]
> @andbortnik is there anything left to do in this task?

Nothing. I'll close the task
