### ISSUE TITLE
Fix forbidden for downloading blockchain binary files

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#267]
Example:
GET http://3.143.205.184:8555/blockchain/blockchain-states/0/0/0/0/0/0/0/0/000000000%21-arf.msgpack.xz
403 Forbidden
nginx/1.19.10

Ensure for blockchunks

**Comment by dmugtasimov** [comment]
This is because of 
```
/var/lib/blockchain/blockchain-states/0/0/0/0/0/0/0/0:
total 48
-r-------- 1 root root 46908 Jul 22 22:15 '000000000!-arf.msgpack.xz'
```

Should be read for all and group

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/281

**Comment by andbortnik** [comment]
@dmugtasimov It turns out that's because of this https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp

>  The file is readable and writable only by the creating user ID.

This function is used by `atomicwrites`

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you
