### ISSUE TITLE
Add favicon to the node and use "thenewboston node" as title

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#268]
TODO:
- Add favicon to the node and use "thenewboston node" as title
- Is there a way to make "thenewboston node {replace with node identifier}"? - which should change in case it is changed in config

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/374

> which should change in case it is changed in config

Can you clarify, please?

**Comment by dmugtasimov** [comment]
@andbortnik you already did what I asked for.

Please, address PR comment

**Comment by andbortnik** [comment]
@dmugtasimov Answered in the PR

**Comment by dmugtasimov** [comment]
@andbortnik thank, merged

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/389
