### ISSUE TITLE
Implement blockchain business logic in a framework and storage agnostic way

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-node#27]

**Comment by dmugtasimov** [comment]
Subtask: https://github.com/thenewboston-developers/thenewboston-node/issues/47

**Comment by dmugtasimov** [comment]
Subtask: https://github.com/thenewboston-developers/thenewboston-node/issues/48

**Comment by dmugtasimov** [comment]
Subtask: https://github.com/thenewboston-developers/thenewboston-node/issues/49

**Comment by dmugtasimov** [comment]
Subtask: https://github.com/thenewboston-developers/thenewboston-node/issues/50

**Comment by dmugtasimov** [comment]
Subtask: https://github.com/thenewboston-developers/thenewboston-node/issues/51

**Comment by dmugtasimov** [comment]
Subtask: https://github.com/thenewboston-developers/thenewboston-node/issues/52

**Comment by dmugtasimov** [comment]
Subtask: https://github.com/thenewboston-developers/thenewboston-node/issues/59

**Comment by dmugtasimov** [comment]
@buckyroberts Let's consider this task as done. Although I am pretty sure there are some bugs on edge cases and the unittest coverage (in terms of business cases) can and should be improved. I will review the code next week adding more unittests, but I need some fresh eyes to take a look (if you have your own capacity for this it would be great).
