### ISSUE TITLE
Add blockchain state validation (with signature)

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#270]
TODO:
- When a node produces a blockchain state it signs it or attaches a signature received from primary validator (in latter case it should validate the correctness of the signature)
- Use `SignableMixin`, it may require nest the blockchain state into `message` attribute
- Blockchain state validation must optionally include validation that the current primary validator has signed it (this can be learned from `primary_validator_schedule` and `last_block_number`
- Also we need to be able to attach a signature from primary validator to locally generated blockchain state (and then validate) - this is because nodes will be receiving just signatures which they should validate against current blockchain state
- Invalid blockchain state cannot be added to the blockchain

**Comment by andbortnik** [comment]
@dmugtasimov Ready for review https://github.com/thenewboston-developers/thenewboston-node/pull/365
This feature is implemented
> - Use SignableMixin, it may require nest the blockchain state into message attribute

**Comment by dmugtasimov** [comment]
@andbortnik great work. Thank you, merged. Please, address comments in another PR

**Comment by andbortnik** [comment]
@dmugtasimov Some refactoring https://github.com/thenewboston-developers/thenewboston-node/pull/375

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you

**Comment by dmugtasimov** [comment]
@andbortnik I got the point. We should allow for a blockchain to be not signed, but if it is signed then the signature should be valid.

**Comment by andbortnik** [comment]
>> Do we attach the PV signature and validate it during generate_blockchain_state?

>Yes

>>How do we make sure that the PV has generated the signature before the moment when regular nodes ask the PV for the signature

> regular node will not ask PV for the signature. it will receive the signature. and once it receives it will create the blockchain state (from its local blockchain) and validate the signature against the blockchain state. if it matches it will attach the signature to the blockchain state

Right now `generate_blockchain_state` is called every `snapshot_period_in_blocks` blocks. The PV can sign the new blockchain state. But regular nodes and CVs have to wait until they get the signature and can call `generate_blockchain_state`. So only PV can make a new blockchain state by schedule. Every other node should just ignore `snapshot_period_in_blocks` and wait for the signature. Is that right? Do we implement it in the task?

**Comment by dmugtasimov** [comment]
@andbortnik no, let's keep creating the snapshots as before, but only current PV adds signature to its snapshots. The other nodes just add snapshots with current PV as signer, but no signature attached. Later we will add signature attaching feature. Also we will probably treat unsigned snapshots differently (for example do not list them in API, but use just for internal performance optimization).

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/405

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you

**Comment by dmugtasimov** [comment]
@andbortnik is there anything else left to do about this task? Otherwise, please, close and move to done.
