### ISSUE TITLE
Unmock get_latest_blockchain_state_meta_by_network_address()

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#278]
TODO:
- [DEPENDS ON] https://github.com/thenewboston-developers/thenewboston-node/issues/252
- Make GET `/api/v1/blockchain-states-meta/?limit=1&ordering=-last_block_number`
- Use requests library
- Unittest
- Use HTTPretty to mock node

**Comment by fonar** [comment]
PR #331 
@dmugtasimov please review

**Comment by dmugtasimov** [comment]
@fonar merged, thank you. I am assigning the tasks to myself to do some refinements

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/thenewboston-node/pull/332
