### ISSUE TITLE
fix and improve INSTALL.rst 

### ISSUE THREAD

**Issue by fonar** [thenewboston-developers/thenewboston-node#300]
1. Python dependencies installation will fail (psycopg2-binary), if "libpq-dev" package is not installed

2. This will fail as git repository is not cloned at this moment
```
#. [if you have not configured it globally] Configure git::

    git config user.name 'Firstname Lastname'
    git config user.email 'youremail@youremail_domain.com'
```
3. It's not clear if its needed or not, better to specify what should be edited
```
    # Edit files if needed
    vim ./local/settings.py
    vim ./local/settings.unittests.py
```
4. In templates/settings.py this can not be replaced at this moment as python project depdendencies is not yet installed
`<replace with a value produced with `make generate-signing-key`>`

**Comment by dmugtasimov** [comment]
PR: https://github.com/thenewboston-developers/thenewboston-node/pull/302

**Comment by dmugtasimov** [comment]
@fonar please, address the PR comments

**Comment by dmugtasimov** [comment]
@fonar merge, thank you
