### ISSUE TITLE
Add clickable table of content to "thenewboston blockchain format" to simplify navigation

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#306]
Here https://github.com/thenewboston-developers/thenewboston-node/wiki/thenewboston-blockchain-format

Be aware the wiki is autogenerate therefore the changes should be made to the template.

**Comment by fonar** [comment]
@dmugtasimov done, please review.
Will that work If I'll link PR's to issues like that?
![image](https://user-images.githubusercontent.com/5008719/129613952-23b27b42-e313-450b-8dc8-017ece32935d.png)

**Comment by dmugtasimov** [comment]
@fonar yes

**Comment by dmugtasimov** [comment]
@fonar thank you, merged
