### ISSUE TITLE
Blockchain state meta API returns 404 for compressed files

### ISSUE THREAD

**Issue by andbortnik** [thenewboston-developers/thenewboston-node#372]
Blockchain states meta API returns wrong `url_path` and `urls` fields if the file is compressed:
```
> GET /api/v1/blockchain-states-meta/-1/
```
```
{
    "last_block_number": null,
    "url_path": "/blockchain/blockchain-states/0/0/0/0/0/0/0/0/0000000000000000000!-blockchain-state.msgpack",
    "urls": [
        "http://3.143.205.184:8555/blockchain/blockchain-states/0/0/0/0/0/0/0/0/0000000000000000000!-blockchain-state.msgpack"
    ]
}
```

Expected result:
```
{
    "last_block_number": null,
    "url_path": "/blockchain/blockchain-states/0/0/0/0/0/0/0/0/0000000000000000000!-blockchain-state.msgpack.xz",
    "urls": [
        "http://3.143.205.184:8555/blockchain/blockchain-states/0/0/0/0/0/0/0/0/0000000000000000000!-blockchain-state.msgpack.xz"
    ]
}
```

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/373

**Comment by dmugtasimov** [comment]
@andbortnik please, address comments

**Comment by andbortnik** [comment]
@dmugtasimov Please see the changes

**Comment by dmugtasimov** [comment]
@andbortnik please, see my replies. Also take a look at block chuck meta implementation (I merged it today). It does have issue with compressor uncertainty (when `filename` sometime treated as original name and sometimes as actual filename). May you can fix them in the same style. I think we need `original_filename` and `actual_filename` tuple attributes to be explicitly clear what is meant
