### ISSUE TITLE
Suggest unittest code coverage improvements

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#67]
Review the code and unittests and suggest unittest code coverage improvements. Add the suggestions as comments to this task. Once you do it will we will create substasks and prioritized them for implementation.

**Comment by andbortnik** [comment]
1. Omit django project files, abstract methods, and mocks when measure code coverage (https://github.com/thenewboston-developers/thenewboston-node/pull/76). This will increase code coverage from 85% to 88%.
1. Test from scratch:
    - `thenewboston_node/business_logic/blockchain/file_blockchain.py:FileBlockchain`
    - `thenewboston_node/core/utils/collections.py:deep_update`
    - `thenewboston_node/core/middleware.py`
    - `thenewboston_node/core/utils/settings.py`
1. Test negative scenarios for:
    - `thenewboston_node/business_logic/blockchain/base.py:BlockchainBase`
    - `thenewboston_node/business_logic/blockchain/memory_blockchain.py:MemoryBlockchain`
    - `thenewboston_node/business_logic/models/account_balance.py:AccountBalance`
    - `thenewboston_node/business_logic/models/account_root_file.py:AccountRootFile`
    - `thenewboston_node/business_logic/models/base.py:SignableMixin`
    - `thenewboston_node/business_logic/models/block.py:Block`
    - `thenewboston_node/business_logic/models/block_message.py:BlockMessage`
    - `thenewboston_node/business_logic/storages/file_system.py:FileSystemStorage`

**Comment by dmugtasimov** [comment]
@andbortnik Please, work on this one: https://github.com/thenewboston-developers/thenewboston-node/issues/77

I can't assign it to you for some reason. Please, assign it for yourself if possible.

**Comment by dmugtasimov** [comment]
@andbortnik one more subtask: https://github.com/thenewboston-developers/thenewboston-node/issues/79

**Comment by andbortnik** [comment]
@dmugtasimov What about the task? Do we close it?

**Comment by dmugtasimov** [comment]
yep, still we going to use it later to create more task about test coverage
