### ISSUE TITLE
Improve unittesting for thenewboston_node.business_logic.storages.file_system.py:FileSystemStorage

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#77]
Cover at least these cases if they are not already covered:
1. Each method coverage
2. All edge cases
3. All compression type choice on save
4. Decompression for each type of compression

**Comment by andbortnik** [comment]
@dmugtasimov Before I can proceed to unit testing itself some refactoring were needed. Please see the description here https://github.com/thenewboston-developers/thenewboston-node/pull/80#issue-614433274

**Comment by andbortnik** [comment]
@dmugtasimov Please see PR https://github.com/thenewboston-developers/thenewboston-node/pull/82

**Comment by dmugtasimov** [comment]
@andbortnik thank you. I merged it. I added a couple of minor comments to the PR. Feel free to fix them in any up coming PR. Move the task to done if we should consider it as such.

**Comment by andbortnik** [comment]
@dmugtasimov Minor fixes requested https://github.com/thenewboston-developers/thenewboston-node/pull/94

**Comment by dmugtasimov** [comment]
merged

**Comment by andbortnik** [comment]
@dmugtasimov Just another couple of tests and we can close the task https://github.com/thenewboston-developers/thenewboston-node/pull/96/files

**Comment by dmugtasimov** [comment]
@andbortnik merged, thanks
