### ISSUE TITLE
Support compacting all known block keys

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#78]
See how it is implemented for account root file. Consider all nested keys

**Comment by andbortnik** [comment]
@dmugtasimov Please see PR https://github.com/thenewboston-developers/thenewboston-node/pull/83/

**Comment by dmugtasimov** [comment]
@andbortnik I like the PR in general. Please, implement the requested improvements and I will merge it (do not forget to rebase).

**Comment by andbortnik** [comment]
@dmugtasimov Fixed. Please take another look

**Comment by dmugtasimov** [comment]
@andbortnik just did, small but important change is required

**Comment by andbortnik** [comment]
@dmugtasimov Please check the comment https://github.com/thenewboston-developers/thenewboston-node/pull/83#discussion_r615240036

**Comment by dmugtasimov** [comment]
@andbortnik replied

**Comment by andbortnik** [comment]
@dmugtasimov Fixed

**Comment by dmugtasimov** [comment]
@andbortnik merged. Please, generate 1000 blocks blockchain with thenewboston_node/cli/generate_blockchain.py and comment here how many compressed byte per block on average we have now. It used to be about 280

**Comment by andbortnik** [comment]
@dmugtasimov Not that big of a change: 276
