### ISSUE TITLE
Cover regular and edge cases of thenewboston_node.business_logic.blockchain.base.BlockchainBase

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#79]
You are testing thenewboston_node.business_logic.blockchain.base.BlockchainBase by testing thenewboston_node.business_logic.blockchain.memory_blockchain.MemoryBlockchain (we already have some tests implemented this way)

There are some backup methods that are overridden in thenewboston_node.business_logic.blockchain.memory_blockchain.MemoryBlockchain . These methods should have separate tests.

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/145

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/185

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you. If there is nothing else to do about this task. Please, move it to done and close.
