### ISSUE TITLE
Store hexadecimals as binary

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#84]
Blockchain structures have various hexadecimal values: account numbers, node identifiers, signatures, hashes. All of them are represented in memory and JSON as hexadecimal strings. We probably can live with it, but when it come to persisting to disk we would like store them as true binary.

Implement this feature by overriding from_messagepack() and to_messagepack() methods. This should reduce size of the persisted data (before compression about 2 times, implement a unittest proving that).

Please, be aware that messagepack has some automatic utf-8 decoding with string. Make sure you do not mess up with it.

**Comment by andbortnik** [comment]
@dmugtasimov I implemented it (https://github.com/thenewboston-developers/thenewboston-node/pull/114) but some interesting thing turns out.

If I measure block serialized to message pack it gets 33% smaller. But when I generate blockchain and calculate average block size it increases from 276 bytes per block to 307 which is 11% larger. It turns out that XZ compression works much worse with binary data.

What do you think?

**Comment by dmugtasimov** [comment]
@andbortnik I think you have an implementation bug

**Comment by andbortnik** [comment]
@dmugtasimov See raw file size:
```
-rw-rw-r-- 1 andy andy  83144 Apr 20 16:30 compact_values
-rw-rw-r-- 1 andy andy 124741 Apr 20 16:31 original_values
```

After xz compression:
```
-rw-rw-r-- 1 andy andy 31320 Apr 20 16:30 compact_values.xz
-rw-rw-r-- 1 andy andy 27768 Apr 20 16:31 original_values.xz
```

**Comment by dmugtasimov** [comment]
@andbortnik I requested changes to the PR. Later I will take a look to figure out what to do with it. Increase of compressed size looks very strange.

**Comment by andbortnik** [comment]
Just to compare:
```
-r--r--r-- 1 andy andy  83081 Apr 20 21:59 compact_values
-r--r--r-- 1 andy andy  70238 Apr 20 21:56 compact_values_and_subkeys
-r--r--r-- 1 andy andy 124739 Apr 20 21:57 original
```
XZ compression:
```
-r--r--r-- 1 andy andy 26836 Apr 20 21:56 compact_values_and_subkeys.xz
-r--r--r-- 1 andy andy 31400 Apr 20 21:59 compact_values.xz
-r--r--r-- 1 andy andy 27736 Apr 20 21:57 original.xz
```

**Comment by dmugtasimov** [comment]
@andbortnik See what I told you. It was an implementation bug: forgotten keys conversion

**Comment by andbortnik** [comment]
@dmugtasimov It wasn't a bug. I just implemented the main part and decided to check the effect of it first. And I was surprised that files got bloated instead. Wanted you to know that so I wouldn't spend any time further. Anyway the final change is not what we expected to have.
