### ISSUE TITLE
Support memo field per transaction

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#85]
Similar to how it is implemented in alpha version

**Comment by mrbusysky** [comment]
Also, a good idea to limit the characters/symbols to ones that are only useable in json.

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/119

**Comment by dmugtasimov** [comment]
@andbortnik fix the comment and merge it yourself

**Comment by dmugtasimov** [comment]
@andbortnik please, also add a unittest to make sure that message pack does not mess up utf-8 specific characters (use characters outside ascii - Russian is fine) 

My point of concern is here https://github.com/msgpack/msgpack-python

```
Packer

use_bin_type=True by default. bytes are encoded in bin type in msgpack. If you are still using Python 2, you must use unicode for all string types. You can use use_bin_type=False to encode into old msgpack format.
encoding option is removed. UTF-8 is used always.

Unpacker

raw=False by default. It assumes str types are valid UTF-8 string and decode them to Python str (unicode) object.
encoding option is removed. You can use raw=True to support old format.
```

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/120

**Comment by dmugtasimov** [comment]
merged thanks
