### ISSUE TITLE
Review and implement or delete not implemented unittests

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#86]

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/388#pullrequestreview-761904403 and check my comments

**Comment by dmugtasimov** [comment]
@andbortnik I merged the PR. Please, address the comments in a new one.

**Comment by andbortnik** [comment]
@dmugtasimov Don't you think `BlockchainStateMessage.account_states`/`BlockMessage.updated_account_states` structure should be redesigned? Right now it looks like:
```
class BlockchainStateMessage(MessageMixin, BaseDataclass):
    account_states: dict[hexstr, AccountState] = field(
        metadata={'example_value': {
            '00f3d2477317d53bcc2a410decb68c769eea2f0d74b679369b7417e198bd97b6': {}
        }}
    )
    """Account number to account state map"""
```
```
class BlockMessage(MessageMixin, BaseDataclass):
    updated_account_states: dict[hexstr, AccountState] = field(
        metadata={'example_value': {
            '657cf373f6f8fb72854bd302269b8b2b3576e3e2a686bd7d0a112babaa1790c6': {}
        }}
    )
```

1. First of all, `dict` is not an ordered structure. So on every serialization/deserialization the order changes. This may produce some diffs in files on different nodes.
2. It's not convenient when `AccountState` has fields like `balance`, `balance_lock`, `node` describing an account but does not include the account_number. So we have to return a pair of objects `account_number, account_state` in methods.
3. It's difficult to add serialization/deserialization logic to `account_states` fields which is needed to remove Node's `fee_account` if it's equal to `account_states`'s one.


So I propose:
1. Make `account_states`/`updated_account_states` a list of `AccountState`
```
class BlockchainStateMessage(MessageMixin, BaseDataclass):
    account_states: list[AccountState] = field(...)
```
```
class BlockMessage(MessageMixin, BaseDataclass):
    updated_account_states: dict[AccountState] = field(...)
```
2. Add `identifier` field to `AccountState` model.
3. We can keep dicts as internal structures to keep all the benefits of fast access

**Comment by dmugtasimov** [comment]
@andbortnik Added as a separate task: https://github.com/thenewboston-developers/thenewboston-node/issues/426

For now it does seem to be a big issue, although some drawbacks you have described are true.

On the other hand having different internal and stored representation would introduce issues we currently do not have. At least extra conversion and validation logic on serialization/deserialization and automatic documentation will fail.

**Comment by dmugtasimov** [comment]
@andbortnik anything else to do in this task?

**Comment by dmugtasimov** [comment]
@andbortnik merged, thank you. if nothing else to do about this task, please, close and move to done
