### ISSUE TITLE
Implement unittests for file blockchain

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#92]
At least take all tests from thenewboston_node/business_logic/tests/test_memory_blockchain and add them for file blockchain as well. This minimum, but I guess we need more tests for file blockchain especially related to various optimizations.

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/125

**Comment by dmugtasimov** [comment]
@andbortnik Thank you. Added questions and requested changes: https://github.com/thenewboston-developers/thenewboston-node/pull/125#pullrequestreview-649918219

**Comment by tspearing** [comment]
Approved

**Comment by andbortnik** [comment]
@dmugtasimov Please review again

**Comment by dmugtasimov** [comment]
@andbortnik I merged. Thank you. Please, fix the comment I made in some other upcoming PR

**Comment by andbortnik** [comment]
Please review the requested fixes https://github.com/thenewboston-developers/thenewboston-node/pull/143

**Comment by dmugtasimov** [comment]
@andbortnik merged

**Comment by dmugtasimov** [comment]
@andbortnik is there anything else to do about this task?
