### ISSUE TITLE
Generate blockchain data structure description from code

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#95]
The aim it to avoid parallel support of documentation, so as soon as you make the change you can regenerate the documentation.

Requirements:
- It must be a CLI tool
- Output is ReStructured mark up

TODO:
- [DONE] Support multiple block types -> done here: https://github.com/thenewboston-developers/thenewboston-node/pull/188
- [DONE] Properly read docstrings for attribute (also allow empty docstrings)
- [DONE] Generate example values with factories (or memory blockchain instead of hardcoding)
- [DONE] Add documentation generation to gitflow actions
- [DONE] Expand object to actual types
- [DONE] Rename account root files to blockchain state
- [DONE] Properly describe datetime type
- [DONE] Review comments of this task for missing TODOs
- [DONE] Add doc generation to linter
- [DONE] Implicit docstrings for dataclasses
- [DONE] Make sure documentation update produces same hashes / signatures, etc (take care to constantify timestamps)
- [DONE] Fix having `"node_type": "PRIMARY_VALIDATOR"`
- [DONE] Add example value for each field
- [DONE] Correctly represent optionality for serialized fields
- [MOVED OUT] Reread the docs and if there are improvement required -> https://github.com/thenewboston-developers/thenewboston-node/issues/218
- [MOVED OUT] Review and update docstrings for dataclass attributes -> https://github.com/thenewboston-developers/thenewboston-node/issues/218

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/127
See how it looks https://github.com/andbortnik/thenewboston-node/tree/95-generate-blockchain-data-structure-documentation/docs/rst
We can generate HTML documentation as well, no development required

**Comment by dmugtasimov** [comment]
@andbortnik these links return HTTP404 for some reason:

Indices and tables
Index
Module Index
Search Page

**Comment by dmugtasimov** [comment]
@andbortnik please, move forward according to how we discussed on the call

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/128

**Comment by dmugtasimov** [comment]
@andbortnik please, rebase

**Comment by andbortnik** [comment]
@dmugtasimov Done

**Comment by dmugtasimov** [comment]
@andbortnik looks great. Thank. I merged it will do some amendments now and maybe will ask for some changes from you.

**Comment by dmugtasimov** [comment]
I will be collecting required changes in this comment. Please, do not work on them until I ask for it explicitly.

**Comment by dmugtasimov** [comment]
Some restructuring: https://github.com/thenewboston-developers/thenewboston-node/pull/147

**Comment by dmugtasimov** [comment]
@andbortnik please, work on https://github.com/thenewboston-developers/thenewboston-node/issues/95#issuecomment-849786255

**Comment by andbortnik** [comment]
@dmugtasimov Some questions:
1. Django management command will conflict with https://github.com/thenewboston-developers/thenewboston-node/pull/144 task. Please review it first.
2. Do you want complex structures like `dict[str, BlockAccountBalance]`, `dict[str, AccountBalance]`, and `list[CoinTransferTransaction]` to be represented in documentation as they are in Python terms, not JSON terms like `object` and `array`?

**Comment by dmugtasimov** [comment]
@andbortnik 
1. OK, will review
2. object[str, BlockAccountBalance] and array[CoinTransferTransaction] is fine. I just need to represent nested type and have it clickable.

**Comment by dmugtasimov** [comment]
@andbortnik 1. done

**Comment by dmugtasimov** [comment]
```

**Comment by dmugtasimov** [comment]
@andbortnik 

```python
@dataclass_json
@dataclass
class AccountBalance:
    """Account balance state"""

    value: int
    """Amount balance value in coins"""

    lock: str
    """Account balance lock"""
```

Now we have to use docstrings even if they are useless (just repeat the name of the attribute without providing any extra information). Fix it. We can keep it for classes, because it is hard to do with `@dataclass` which forces docstring if there is none. But for attributes I we need to use and attribute name (or just empty description) if a docstring is not provided.

**Comment by dmugtasimov** [comment]
@andbortnik consider using `__dataclass_fields__`

**Comment by dmugtasimov** [comment]
@andbortnik also we have `from thenewboston_node.core.utils.misc import humanize_camel_case`

**Comment by dmugtasimov** [comment]
@andbortnik please, implement recursive models traversal instead of hardcoded list of models:

```
BLOCK_MODELS = (
    models.Block,
    models.BlockMessage,
    models.AccountState,
    models.CoinTransferSignedRequest,
    models.CoinTransferSignedRequestMessage,
    models.CoinTransferTransaction,
)

ROOT_ACCOUNT_FILE_MODELS = (
    models.AccountRootFile,
    models.AccountState,
)
```

**Comment by dmugtasimov** [comment]
@andbortnik please, provide requested changes in several PRs, so they do not grow too big

**Comment by dmugtasimov** [comment]
@andbortnik please, reduce amount of hardcoding:

```
BLOCK_SAMPLE = models.Block(
    signer='4d3cf1d9e4547d324de2084b568f807ef12045075a7a01b8bec1e7f013fc3732',
    message_hash='9677f4cbd7aaf32ba9615416f7bd0991b7de1434a7fa2c31add25c3355ef3959',
    signature='d1c49087103b631a58228bdf8fb70d4789259cf22d815e207660cfe8d478ad'
    'ad9c7affe587942203e08be1dc1e14c6dd5a8abd8640f328e45f667a91a7c06a06',
    message=models.BlockMessage(
        block_identifier='d606af9d1d769192813d71051148ef1896e3d85062c31ad3e62331e25d9c96bc',
        block_number=0,
        timestamp=datetime.datetime(2021, 1, 1),
        transfer_request=models.CoinTransferSignedRequest(
            message=models.CoinTransferSignedRequestMessage(
                balance_lock='cb0467e380e032881e3f5c26878da3584f1dc1f2262ef77ba5e1fa7ef4b2821c',
                txs=[
                    models.CoinTransferTransaction(
                        amount=54,
                        recipient='8d3bf5323afa7a8c6bc9418288e96491a0434a98925bf392835bfdb5a4f817ff',
                    ),
                    models.CoinTransferTransaction(
                        amount=5,
                        recipient='4d3cf1d9e4547d324de2084b568f807ef12045075a7a01b8bec1e7f013fc3732',
                        fee=True,
                    ),
                    models.CoinTransferTransaction(
                        amount=1,
                        recipient='1be4f03ab7ea1184dbb5e4ff53b8cf0fe1cc400150ca1476fcd10546c1b3cd6a',
                        fee=True,
                    )
                ]
            ),
            signature='ae74562897f228a3d9bc388eba5037f34393e33813086c103bb5d6fc39a0'
            '23408655057f4ed8593c2d36bc98fb468112fdac186bec616ec2f2ba45c579c02108',
            signer='cb0467e380e032881e3f5c26878da3584f1dc1f2262ef77ba5e1fa7ef4b2821c',
        ),
        updated_account_states={
            '1be4f03ab7ea1184dbb5e4ff53b8cf0fe1cc400150ca1476fcd10546c1b3cd6a':
                thenewboston_node.business_logic.models.account_state_update.AccountStateUpdate(balance=1),
            '4d3cf1d9e4547d324de2084b568f807ef12045075a7a01b8bec1e7f013fc3732':
                thenewboston_node.business_logic.models.account_state_update.AccountStateUpdate(balance=4),
            '8d3bf5323afa7a8c6bc9418288e96491a0434a98925bf392835bfdb5a4f817ff':
                thenewboston_node.business_logic.models.account_state_update.AccountStateUpdate(balance=54),
        },
    ),
)
```

`from_main_transaction()` method could be used instead.

The idea is that whenever we change code we do not have care about changing the documentation as well (well, this should be minimized)

**Comment by dmugtasimov** [comment]
@andbortnik add git flow action, so every time documentation is generated and publicly available.

Also consider adding documentation generation as a part of QA process (sometime lint passes, tests pass, but documentation generation does not)

**Comment by dmugtasimov** [comment]
@andbortnik support multitype blocks in the documentation

**Comment by dmugtasimov** [comment]
@andbortnik I am taking this task to myself for now. Please, let me know when you are back to work to take it back.

**Comment by dmugtasimov** [comment]
Management command: https://github.com/thenewboston-developers/thenewboston-node/pull/181

**Comment by dmugtasimov** [comment]
Code moved: https://github.com/thenewboston-developers/thenewboston-node/pull/182

**Comment by dmugtasimov** [comment]
more moved: https://github.com/thenewboston-developers/thenewboston-node/pull/183

**Comment by dmugtasimov** [comment]
Documentable mixin: https://github.com/thenewboston-developers/thenewboston-node/pull/184

**Comment by dmugtasimov** [comment]
Implicit docstrings: https://github.com/thenewboston-developers/thenewboston-node/pull/189

**Comment by dmugtasimov** [comment]
realistic sample generation: https://github.com/thenewboston-developers/thenewboston-node/pull/190

**Comment by dmugtasimov** [comment]
Autogenerated on github: https://github.com/thenewboston-developers/thenewboston-node/pull/192

**Comment by dmugtasimov** [comment]
Some fixes: https://github.com/thenewboston-developers/thenewboston-node/pull/193

**Comment by dmugtasimov** [comment]
Complex types are properly expanded and some more improvements: https://github.com/thenewboston-developers/thenewboston-node/pull/195

**Comment by dmugtasimov** [comment]
Unittest docs generation: https://github.com/thenewboston-developers/thenewboston-node/pull/196

**Comment by dmugtasimov** [comment]
Implicit dataclass docstrings: https://github.com/thenewboston-developers/thenewboston-node/pull/197

**Comment by dmugtasimov** [comment]
Moment of documentation generation does not affect its content anymore: https://github.com/thenewboston-developers/thenewboston-node/pull/198

**Comment by dmugtasimov** [comment]
Node type attribute removed from example: https://github.com/thenewboston-developers/thenewboston-node/pull/199

**Comment by dmugtasimov** [comment]
Example values: https://github.com/thenewboston-developers/thenewboston-node/pull/200

**Comment by dmugtasimov** [comment]
Corrected "Is mandatory": https://github.com/thenewboston-developers/thenewboston-node/pull/201
