### ISSUE TITLE
Delegate base directory path management from FileBlockchain to file system storage

### ISSUE THREAD

**Issue by andbortnik** [thenewboston-developers/thenewboston-node#98]
Instead of FileBlockchain managing directories where blocks and account root file are stored let's delegate it to storages. So we pass directory to storage on creation and forget about it on `FileBlockchain` level. Like this:
```
block_directory = '...'
block_storage = PathOptimizedFileSystemStorage(path=block_directory)

account_root_files_directory = '...'
account_root_files_storage = PathOptimizedFileSystemStorage(path=account_root_files_directory)
```
This will also enhance security. Right now we pass absolute file paths to storages so you can overwrite something by a mistake. After we pass base directory to the storage it will operate only on files within this directory.

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/118

**Comment by dmugtasimov** [comment]
merged
