### ISSUE TITLE
Make generate_blockchain.py a management command since we decided to stay with Django

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#99]
Make generate_blockchain.py a management command since we decided to stay with Django
Put it to `core` application for now.

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/144

**Comment by dmugtasimov** [comment]
@andbortnik merged. Please, make suggested fixes (see PR comments) and merge them yourself
